language: cpp
sudo: required

dist: bionic
osx_image: xcode11.3

addons:
  homebrew:
    packages:
      - libffi
      - lua
      - ninja
    update: true

# TODO: release branches
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
      env: LUA_VERSION=5.1 CXX=g++
    - os: linux
      arch: amd64
      compiler: gcc
      env: LUA_VERSION=5.2 CXX=g++
    - os: linux
      arch: amd64
      compiler: gcc
      env: LUA_VERSION=5.3 CXX=g++
    - os: linux
      arch: amd64
      compiler: clang
      env: LUA_VERSION=5.3 CXX=clang++

    - os: linux
      arch: ppc64le
      compiler: gcc
      env: LUA_VERSION=5.3 CXX=g++
    - os: linux
      arch: ppc64le
      compiler: clang
      env: LUA_VERSION=5.3 CXX=clang++

    - os: linux
      arch: s390x
      compiler: gcc
      env: LUA_VERSION=5.3 CXX=g++
    - os: linux
      arch: s390x
      compiler: clang
      env: LUA_VERSION=5.3 CXX=clang++

    - os: linux
      arch: arm64
      compiler: gcc
      env: LUA_VERSION=5.3 CXX=g++
    - os: linux
      arch: arm64
      compiler: clang
      env: LUA_VERSION=5.3 CXX=clang++

    - os: osx
      compiler: clang
      env: LUA_VERSION=5.3 CXX=clang++

before_install:
  - |
      if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          sudo apt-get update || exit 1
          sudo apt-get -y install pkg-config ninja-build python3-pip \
              python3-setuptools libffi-dev liblua${LUA_VERSION}-dev || exit 1
          sudo pip3 install meson
      fi
  - |
      if [ "$TRAVIS_OS_NAME" == "osx" ]; then
          pip3 install meson
      fi

script:
  - |
      if [ "$TRAVIS_OS_NAME" == "osx" ]; then
          export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
      fi
  - mkdir build && cd build
  - meson .. -Dlua_version="$LUA_VERSION"
  - ninja all
  - ninja test
