language: cpp
sudo: required

branches:
  only:
    - master
    # release branches
    - /^[0-9]+\.[0-9]+$/
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

dist: bionic
osx_image: xcode11.3

addons:
  # os x dependencies
  homebrew:
    packages:
      - libffi
      - lua
      - ninja
    update: true

  # linux dependencies
  apt:
    packages:
      - pkg-config
      - ninja-build
      - python3-pip
      - python3-setuptools
      - libffi-dev
    update: true

matrix:
  include:
    # x86_64 linux, test all lua versions under gcc + 5.3 under clang
    - os: linux
      arch: amd64
      compiler: gcc
      env: LUA_VERSION=5.1 CXX=g++
    - os: linux
      arch: amd64
      compiler: gcc
      env: LUA_VERSION=5.2 CXX=g++
    - os: linux
      arch: amd64
      compiler: gcc
      env: LUA_VERSION=5.3 CXX=g++
    - os: linux
      arch: amd64
      compiler: clang
      env: LUA_VERSION=5.3 CXX=clang++

    # ppc64le linux, test gcc and clang, 5.3 only
    - os: linux
      arch: ppc64le
      compiler: gcc
      env: LUA_VERSION=5.3 CXX=g++
    - os: linux
      arch: ppc64le
      compiler: clang
      env: LUA_VERSION=5.3 CXX=clang++

    # s390x linux, test gcc and clang, 5.3 only
    - os: linux
      arch: s390x
      compiler: gcc
      env: LUA_VERSION=5.3 CXX=g++
    - os: linux
      arch: s390x
      compiler: clang
      env: LUA_VERSION=5.3 CXX=clang++

    # aarch64 linux, test gcc and clang, 5.3 only
    - os: linux
      arch: arm64
      compiler: gcc
      env: LUA_VERSION=5.3 CXX=g++
    - os: linux
      arch: arm64
      compiler: clang
      env: LUA_VERSION=5.3 CXX=clang++

    # os x, clang, 5.3 only
    - os: osx
      compiler: clang
      env: LUA_VERSION=5.3 CXX=clang++

before_install:
  - |
      if [ "$TRAVIS_OS_NAME" == "linux" ]; then
          sudo apt-get -y install liblua${LUA_VERSION}-dev || exit 1
          sudo pip3 install meson
      fi
  - |
      if [ "$TRAVIS_OS_NAME" == "osx" ]; then
          pip3 install meson
      fi

script:
  - |
      if [ "$TRAVIS_OS_NAME" == "osx" ]; then
          export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
      fi
  - mkdir build && cd build
  - meson .. -Dlua_version="$LUA_VERSION"
  - ninja all
  - ninja test
