name: CI

on: push

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-20.04

    env:
      TARGET: '${{ matrix.config.target }}'
      LUA_VERSIONS: '5.4.2 5.3.6 5.2.4 5.1.5'
      CC: '${{ matrix.config.cc }}'
      RELEASE: '${{ matrix.config.release }}'

    strategy:
      matrix:
        config:
          # x86_64: test gcc, clang, + release mode to catch assert bugs
          - { target: x86_64-linux-gnu, cc: gcc, release: 0 }
          - { target: x86_64-linux-gnu, cc: gcc, release: 1 }
          - { target: x86_64-linux-gnu, cc: clang, release: 0 }
          # 32-bit x86
          - { target: i686-linux-gnu, cc: gcc, release: 0 }
          # all powerpc; powerpc64 disabled for now (broken qemu)
          - { target: powerpc64le-linux-gnu, cc: gcc, release: 0 }
          #- { target: powerpc64-linux-gnu, cc: gcc, release: 0 }
          - { target: powerpc-linux-gnu, cc: gcc, release: 0 }
          # aarch64 and arm
          - { target: aarch64-linux-gnu, cc: gcc, release: 0 }
          - { target: arm-linux-gnueabi, cc: gcc, release: 0 }
          # riscv64 and s390x
          - { target: riscv64-linux-gnu, cc: gcc, release: 0 }
          - { target: s390x-linux-gnu, cc: gcc, release: 0 }
          # mips, m68k; mips disabled for now (broken qemu)
          #- { target: mips-linux-gnu, cc: gcc, release: 0 }
          - { target: m68k-linux-gnu, cc: gcc, release: 0 }
          # x86_64 windows cross, release mode
          - { target: x86_64-w64-mingw32, cc: gcc, release: 1 }

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Prepare environment
        run: sh ./.ci/install-env

      - name: Install samurai
        run: sh ./.ci/install-samu

      - name: Build and test cffi
        run: sh ./.ci/build-cffi

  windows:
    name: Windows
    runs-on: windows-2019

    env:
      LUA_VERSIONS: '5.4.2 5.3.6 5.2.4 5.1.5'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Prepare environment
        run: bash ./.ci/install-env-windows

      - name: Build and test cffi
        run: bash ./.ci/build-cffi-windows

  mac:
    name: MacOS
    runs-on: macos-10.15

    env:
      TARGET: 'darwin'
      LUA_VERSIONS: '5.4.2 5.3.6 5.2.4 5.1.5'
      CC: 'clang'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Prepare environment
        run: sh ./.ci/install-env

      - name: Install samurai
        run: sh ./.ci/install-samu

      - name: Build and test cffi
        run: sh ./.ci/build-cffi
